from gc import callbacks
from swift_types import *


@wrapper
class AVPlayerApi:

    def play(self, filePath: str): ...

    def play_or_pause(self): ...

    def player_status(self) -> bool: ...

    def rate_adjustment(self, adjuster: float): ...

    def rate_reset(self): ...

    def return_currentTime(self) -> float: ...
    
    def return_duration(self) -> float: ...